name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      run: |
        docker buildx build --platform linux/amd64 \
        --output "type=image" \
        --tag "omengye/trojan-go:nightly" \
        --build-arg REF=${{ github.sha }} \
        --file Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:trojan-go"
        push: true
        tags: omengye/trojan-go:nightly