name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare
      id: prepare
      run: |
        echo ::set-output name=docker_platforms::linux/amd64
        echo ::set-output name=docker_image::omengye/trojan-go
        echo ::set-output name=ref::${{ github.sha }}

    - name: Build docker image
      run: |
        docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
        --output "type=image" \
        --tag "${{ steps.prepare.outputs.docker_image }}:nightly" \
        --build-arg REF=${{ steps.prepare.outputs.ref }} \
        --file Dockerfile .
